In [49]:
#Numpy- Numeric Python
# Most powerful package - Library

#Numpy- Dimensions
# A-One Dimensionaal Array
# [A,B] || [ A
             #B ]-Two Dimensional Array- Row ||column
# Three Dimensional
# Array-Storing,Manipulating,Similar Data Type
# Faster than any mathematical functions
# Convenient compared to other packages
# Memory Efficiency
# Support Multi Dimensional Arrays
#speed(Numpy operations)>speed(Lists operations)
#size(Numpy operations)<size(Lists operations)
# memory optimizatin(Numpy)>memory optimization(List operations)

In [ ]:
# Install numpy - pip3 install numpy // pip install numpy

In [ ]:
import numpy as np

In [ ]:
# create a numpy array
#1D array
arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
# creating 2D array - Matrix
arr2D = np.array([
    [0,0,0],[0,0,0]
])
print(arr2D)

[[0 0 0]
 [0 0 0]]


In [ ]:
allZeros=np.zeros((2,3))
print(allZeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
allOnes=np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
allConstant=np.full((2,3),6)
print(allConstant)

[[6 6 6]
 [6 6 6]]


In [ ]:

# Create an identity matrix - I - square Matrix
identity = np.eye(4)
print(identity)


# Identity Matrix - Aii = 1 && Aij = 0
# For all a Belongs to R MxN
#Aij -

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# creating random matrices


# between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.50976436 0.67051646 0.99452458]
 [0.12148425 0.17056955 0.34144498]
 [0.09309476 0.75031192 0.4873545 ]]
[[19 13 13]
 [11 16 19]
 [10 13 11]]


In [ ]:
# Array properties
arr=np.array(([1,2,3,4],[2,3,4,5]))
print(arr)
# Shape of the array
print(f'The shape of the array is {arr.shape}')
# Size of array
print(f'The size of the array is {arr.size}')
#Datatype of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]
The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [ ]:
# Indexing and slicing


#Access the elements in 1D Array
arr = np.array([1,2,3,4,])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])

# Access the element in 2D Array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr)
print(arr2[1,1])
print(arr2[0,:]) # First row with all the columns
print(arr2[:,0]) # First column with all the rows

[1 2 3 4]
4
[1 2 3]
[1 2 3 4]
3
[1 2 3]
[1 2]


In [ ]:
# l1 = []
# [l1.append(_) for _ in range(10)]
l1 = np.arange(10,-10,-3)

print(l1)

[10  7  4  1 -2 -5 -8]


In [ ]:
# Mathematcial operations
a=np.array([1,2,3])
b=np.array([3,4,5])
print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
# Matrix multiplication
b1=np.array([[1,2,3],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])

# Dot product  ---- Product= AB -- A m x n -- B n x p
c = np.dot(b1,b2)
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [ ]:
import numpy as np

In [ ]:
# Recap
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#Dot produt - mxn || nxp
arr1 = np.random.randint(1,2,(1,2))

In [ ]:
arr.shape
arr1.shape

(1, 2)

In [ ]:
result = np.dot(arr1,arr)

In [ ]:
print(result)

[[5 7 9]]


In [ ]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[11 13 16]
 [14 11 10]
 [19 18 10]]


In [ ]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#r1 .I
result2 = np.dot(r2,r1)

In [ ]:
print(result2)

[[11. 13. 16.]
 [14. 11. 10.]
 [19. 18. 10.]]


In [ ]:
# M .I = I .M = M
# A.B != B . A

In [ ]:
# Mathematical operations
# + - * /
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [ ]:
print(t1)
print(t2)

[[3 5 4]
 [3 5 3]
 [5 5 5]]
[[3 3 3]
 [5 3 4]
 [3 5 3]]


In [ ]:
t3 = t1 + t2

In [ ]:
t3

array([[ 6,  8,  7],
       [ 8,  8,  7],
       [ 8, 10,  8]])

In [ ]:
# Matrix multiplication
result = np.dot(arr1,arr)

In [ ]:
# statistical operaations
mean = t3.mean()
max = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [ ]:
print(mean)
print(max)
print(median)

7.777777777777778
10
8.0


In [ ]:
print(std)

1.0304020550550783


In [ ]:
print(var)

1.0617283950617287


In [ ]:
std =np.std(t3)

In [ ]:
std + std

2.0608041101101566

In [ ]:
std  * std

1.0617283950617287

In [ ]:
# trignomertic functions
# sin(x)
#cos(x)
#tan(x) - sin(x) / cos(x)
#cosec - 1 / sin(x)
#sec - 1 / cos(x)
#cot -1 / tan(x)
#
angles = np.array([0,15,30,45,60,75,90])

# Sin (array)
result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [ ]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [ ]:
arr = np.array([1,2,3,4,5,6])
#reshape the array
reshapearr = arr.reshape(3,2)
print(reshapearr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#convert / flatten any n dim array
flattenarr = arr.flatten()
print(flattenarr)

[1 2 3 4 5 6]


In [ ]:
# Stacking the data

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

arr3 = np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")


#vertical stacking
arr3 = np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

#Horizantal Stacking
arr4 = np.hstack((arr1,arr2))
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [ ]:
# filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr > 40]

print(farr)

[50 60 70 80]
